--- 
:distance_spec:

  # default, as is
  - - {}
    - 1

  # ignore (exclude) adjectives and particles
  - - :excl: [a, t]
    - 1

  # consider (include) only substantives
  - - :incl: s
    - 2

  # consider (include) only synonyms
  - - :incl: y
    - 4

  # sort the tokens when comparing
  - - :sort: true
    - 4

:default_coeff: 20
